= Policies for Hypershift cluster

Every deployed cluster needs some configuration done. While the authentication can be setup via the `HostedCluster` resource it takes policies to deploy authorization and additional operators to the cluster.

In this document we set up:

* Authorization (cluster-admin for the `admin` user)
* Pipelines Operator
* OpenShift Gitops Operator
* Serverless Operator

== Prerequisites

Right now we are creating these policies as YAML resources on the bastion VM. These can/will be converted into a GitOps repository at a later point in time.

. Create a directory to hold the policy files:
+
[source,sh]
----
mkdir ${HOME}/policies
----

. Create a namespace to hold all the policies:
+
[source,sh]
----
cat << EOF >$HOME/policies/namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdp-policies
EOF
----

. Create the namespace:
+
[source,sh]
----
oc apply -f $HOME/policies/namespace.yaml
----

== Set up authorization

The htpasswd authentication that has been set up during cluster deployment includes a user named `admin`. This user should have cluster admin privileges because when authentication is deployed during cluster deploy no `kubeadmin` user gets created - and therefore it would be impossible to log into the OpenShift console with administrative privileges.

The clusters are all labeled with `type: sandbox` - which is the selector that we will use to deploy the policies.

. Create a directory to hold the files:
+
[source,sh]
----
mkdir -p ${HOME}/policies/authorization
----

. Create a policy to create a ClusterRoleBinding:
+
[source,sh]
----
cat << EOF >$HOME/policies/authorization/policy.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: admin-authorization
  namespace: rhdp-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: admin-authorization
      spec:
        remediationAction: enforce
        pruneObjectBehavior: DeleteIfCreated
        severity: medium
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              annotations:
                rbac.authorization.kubernetes.io/autoupdate: "true"
              name: admin-authorization
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin
            subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: User
              name: admin
EOF
----

. Create a Placement Rule:
+
[source,sh]
----
cat << EOF >$HOME/policies/authorization/placementrule.yaml
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: admin-authorization
  namespace: rhdp-policies
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      type: sandbox
EOF
----

. Create a Placement Binding:
+
[source,sh]
----
cat << EOF >$HOME/policies/authorization/placementbinding.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: admin-authorization
  namespace: rhdp-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: admin-authorization
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: admin-authorization
EOF
----

. Create a kustomization file:
+
[source,sh]
----
cat << EOF >$HOME/policies/authorization/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- policy.yaml
- placementrule.yaml
- placementbinding.yaml
EOF
----

. Apply the policy to the hub cluster:
+
[source,sh]
----
oc apply -k $HOME/policies/authorization
----

== Install the OpenShift Pipelines operator

The clusters are all labeled with `type: sandbox` - which is the selector that we will use to deploy the policies.

. Create a directory to hold the files:
+
[source,sh]
----
mkdir -p ${HOME}/policies/pipelines
----

. Create a policy to create the OpenShift Pipelines Operator subscription:
+
[source,sh]
----
cat << EOF >$HOME/policies/pipelines/policy.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-pipelines-installed
  namespace: rhdp-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-pipelines-installed
      spec:
        remediationAction: enforce
        pruneObjectBehavior: DeleteIfCreated
        severity: medium
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: openshift-pipelines
              namespace: openshift-operators
            spec:
              channel: pipelines-1.8
              installPlanApproval: Automatic
              name: openshift-pipelines-operator-rh
              source: redhat-operators
              sourceNamespace: openshift-marketplace
EOF
----

. Create a Placement Rule:
+
[source,sh]
----
cat << EOF >$HOME/policies/pipelines/placementrule.yaml
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-pipelines-installed
  namespace: rhdp-policies
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      type: sandbox
EOF
----

. Create a Placement Binding:
+
[source,sh]
----
cat << EOF >$HOME/policies/pipelines/placementbinding.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-pipelines-installed
  namespace: rhdp-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: openshift-pipelines-installed
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: openshift-pipelines-installed
EOF
----

. Create a kustomization file:
+
[source,sh]
----
cat << EOF >$HOME/policies/pipelines/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- policy.yaml
- placementrule.yaml
- placementbinding.yaml
EOF
----

. Apply the policy to the hub cluster:
+
[source,sh]
----
oc apply -k $HOME/policies/pipelines
----

== Install the OpenShift GitOps operator

The clusters are all labeled with `type: sandbox` - which is the selector that we will use to deploy the policies.

. Create a directory to hold the files:
+
[source,sh]
----
mkdir -p ${HOME}/policies/gitops
----

. Create a policy to create the OpenShift gitops Operator subscription:
+
[source,sh]
----
cat << EOF >$HOME/policies/gitops/policy.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-installed
  namespace: rhdp-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-gitops-installed
      spec:
        remediationAction: enforce
        pruneObjectBehavior: DeleteIfCreated
        severity: medium
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: openshift-gitops-operator
              namespace: openshift-operators
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: openshift-gitops-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
EOF
----

. Create a Placement Rule:
+
[source,sh]
----
cat << EOF >$HOME/policies/gitops/placementrule.yaml
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-installed
  namespace: rhdp-policies
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      type: sandbox
EOF
----

. Create a Placement Binding:
+
[source,sh]
----
cat << EOF >$HOME/policies/gitops/placementbinding.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-gitops-installed
  namespace: rhdp-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: openshift-gitops-installed
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: openshift-gitops-installed
EOF
----

. Create a kustomization file:
+
[source,sh]
----
cat << EOF >$HOME/policies/gitops/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- policy.yaml
- placementrule.yaml
- placementbinding.yaml
EOF
----

. Apply the policy to the hub cluster:
+
[source,sh]
----
oc apply -k $HOME/policies/gitops
----

== Install the OpenShift Serverless operator

The clusters are all labeled with `type: sandbox` - which is the selector that we will use to deploy the policies.

. Create a directory to hold the files:
+
[source,sh]
----
mkdir -p ${HOME}/policies/serverless
----

. Create a policy to create the OpenShift serverless Operator subscription:
+
[source,sh]
----
cat << EOF >$HOME/policies/serverless/policy.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-serverless-installed
  namespace: rhdp-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-serverless-installed
      spec:
        remediationAction: enforce
        pruneObjectBehavior: DeleteIfCreated
        severity: medium
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: openshift-serverless-operator
              namespace: openshift-operators
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: serverless-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: knative-serving
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: knative-eventing
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.knative.dev/v1alpha1
            kind: KnativeServing
            metadata:
              name: knative-serving
              namespace: knative-serving
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.knative.dev/v1alpha1
            kind: KnativeEventing
            metadata:
              name: knative-eventing
              namespace: knative-eventing
EOF
----

. Create a Placement Rule:
+
[source,sh]
----
cat << EOF >$HOME/policies/serverless/placementrule.yaml
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-serverless-installed
  namespace: rhdp-policies
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      type: sandbox
EOF
----

. Create a Placement Binding:
+
[source,sh]
----
cat << EOF >$HOME/policies/serverless/placementbinding.yaml
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-serverless-installed
  namespace: rhdp-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: openshift-serverless-installed
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: openshift-serverless-installed
EOF
----

. Create a kustomization file:
+
[source,sh]
----
cat << EOF >$HOME/policies/serverless/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- policy.yaml
- placementrule.yaml
- placementbinding.yaml
EOF
----

. Apply the policy to the hub cluster:
+
[source,sh]
----
oc apply -k $HOME/policies/serverless
----
