= Building and publishing a Gitea Operator using the Ansible Operator SDK 1.2

== Install Operator SDK

[NOTE]
The following instructions have been written for RHEL 8. But this entire process also works on macOS - and where appropriate the necessary adjustments and commands have been provided.

In order to build an operator you need to install the Operator SDK binaries on your machine. The current release is 1.2.0 (as of 2020/11/17). In order to follow this lab it is recommended you stick to this release as future updates may break the process. This lab will be updated on a best effort basis up to keep up with Operator SDK releases.

. Install the Operator SDK on your machine:
+
.Linux
[source,sh]
----
RELEASE_VERSION=v1.2.0

curl -L https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk-$RELEASE_VERSION-x86_64-linux-gnu -o operator-sdk
curl -L https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/ansible-operator-$RELEASE_VERSION-x86_64-linux-gnu -o ansible-operator
curl -L https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/helm-operator-$RELEASE_VERSION-x86_64-linux-gnu -o helm-operator

chmod +x operator-sdk ansible-operator helm-operator

sudo chown root:root operator-sdk ansible-operator helm-operator
sudo mv operator-sdk ansible-operator helm-operator /usr/local/bin
----
+
.MacOS
[source,sh]
----
RELEASE_VERSION=v1.2.0

curl -L https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk-$RELEASE_VERSION-x86_64-apple-darwin -o operator-sdk
curl -L https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/ansible-operator-$RELEASE_VERSION-x86_64-apple-darwin -o ansible-operator
curl -L https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/helm-operator-$RELEASE_VERSION-x86_64-apple-darwin -o helm-operator

chmod +x operator-sdk ansible-operator helm-operator

mv operator-sdk ansible-operator helm-operator ~/bin
----

. Set up a Python 3 virtualenv with ansible tools and the OpenShift and Kubernetes Python libraries.
+
[NOTE]
You may need to install `virtualenv` on a system level first using `pip3 install virtualenv`. You may also need to install `gcc`, `make` and `python3-devel` on the Linux system first.
+
[source,sh]
----
# For Linux (RHEL 8) only
sudo yum -y install gcc python3-devel virtualenv make

# For all platforms
virtualenv -p $(which python3) ~/virtualenvs/ansible-operator
source ~/virtualenvs/ansible-operator/bin/activate
pip install -U pip
pip install ansible==2.9.14
pip install ansible-runner==1.4.6
pip install ansible-runner-http==1.0.0
pip install kubernetes==11.0.0
pip install openshift==0.11.2
----

== Create the Gitea operator

The Ansible logic for the operator has already been written. You simply take the roles and the associated playbook and turn them into an Ansible Operator.

. Clone the repository containing the roles:
+
[source,sh]
----
cd $HOME
git clone https://github.com/redhat-gpte-devopsautomation/ansible-operator-roles
cd ansible-operator-roles
git checkout update_alpha1
cd $HOME
----

. Create new operator directory and initialize it
+
[source,sh]
----
mkdir $HOME/gitea-operator
cd $HOME/gitea-operator
operator-sdk init --plugins=ansible.sdk.operatorframework.io/v1 --domain=opentlc.com
operator-sdk create api --group gpte --version v1alpha1 --kind Gitea --generate-playbook
----

. Replace the playbook and roles with the ones you cloned before:
+
[source,sh]
----
rm -rf roles/* playbooks/*
cp -R $HOME/ansible-operator-roles/roles/postgresql-ocp ./roles
cp -R $HOME/ansible-operator-roles/roles/gitea-ocp ./roles
cp $HOME/ansible-operator-roles/playbooks/gitea.yaml ./playbooks/gitea.yml
----

. Examine the `watches.yaml` file:
+
[source,sh]
----
cat ./watches.yaml
----
+
.Sample Output
[source,texinfo]
----
---
# Use the 'create api' subcommand to add watches to this file.
- version: v1alpha1
  group: gpte.opentlc.com
  kind: Gitea
  playbook: playbooks/gitea.yml
# +kubebuilder:scaffold:watch
----
+
This is the main configuration for the Ansible Operator. The group, version, and kind come from the command you used to create the skeleton. The playbook uses the `gitea.yml` filename. In the next step, you see how the file ends up in the `/opt/ansible` location.

. Examine the Dockerfile in the operator directory:
+
[source,sh]
----
cat Dockerfile
----
+
.Sample Output
[source,texinfo]
----
FROM quay.io/operator-framework/ansible-operator:v1.2.0

COPY requirements.yml ${HOME}/requirements.yml
RUN ansible-galaxy collection install -r ${HOME}/requirements.yml \
 && chmod -R ug+rwx ${HOME}/.ansible

COPY watches.yaml ${HOME}/watches.yaml
COPY roles/ ${HOME}/roles/
COPY playbooks/ ${HOME}/playbooks/
----
+
Note the source image for the container image that is being built and observe that all the Dockerfile does is copy the roles, playbook, and watches files into the container image.

== Deploy the CRD

The next step is to deploy the Custom Resource Definition into the cluster. Without the CRD OpenShift does not know that the object to be managed by your operator exists.

. Make sure you are logged into OpenShift as a user with `cluster-admin` permissions.
+
[source,sh]
----
oc login -u <user with cluster-admin privileges>
----

. Deploy the CRD:
+
[source,sh]
----
make install
----
+
.Sample Output
[source,texinfo]
----
./bin/kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/giteas.gpte.opentlc.com created
----

== Test the operator

The Operator SDK contains capabilities to test your operator without having to build the operator container image or deploying the operator to the cluster. This is a really convenient capability while developing and testing your operator.

. Run the operator from your local machine
+
[source,sh]
----
make run
----
+
.Sample Output
[source,texinfo]
----
/usr/local/bin/ansible-operator run
{"level":"info","ts":1605644107.4685068,"logger":"cmd","msg":"Version","Go Version":"go1.15.3","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.2.0","commit":"215fc50b2d4acc7d92b36828f42d7d1ae212015c"}
{"level":"info","ts":1605644107.47265,"logger":"cmd","msg":"WATCH_NAMESPACE environment variable not set. Watching all namespaces.","Namespace":""}
I1117 15:15:08.523317   65598 request.go:621] Throttling request took 1.019239497s, request: GET:https://api.cluster-wkosp.red.osp.opentlc.com:6443/apis/packages.operators.coreos.com/v1?timeout=32s
{"level":"info","ts":1605644110.4810178,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1605644110.4826908,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_GITEA_GPTE_OPENTLC_COM","default":2}
{"level":"info","ts":1605644110.483025,"logger":"cmd","msg":"Environment variable not set; using default value","Namespace":"","envVar":"ANSIBLE_DEBUG_LOGS","ANSIBLE_DEBUG_LOGS":false}
{"level":"info","ts":1605644110.4830415,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"gpte.opentlc.com","Options.Version":"v1alpha1","Options.Kind":"Gitea"}
{"level":"info","ts":1605644110.4850101,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1605644110.4852607,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1605644110.485385,"logger":"controller","msg":"Starting EventSource","controller":"gitea-controller","source":"kind source: gpte.opentlc.com/v1alpha1, Kind=Gitea"}
{"level":"info","ts":1605644110.585879,"logger":"controller","msg":"Starting Controller","controller":"gitea-controller"}
{"level":"info","ts":1605644110.5859401,"logger":"controller","msg":"Starting workers","controller":"gitea-controller","worker count":2}
----

. Leave the operator running and open a second shell to your bastion.
. Create a new project to run your Gitea instance in
+
[source,sh]
----
oc new-project gitea
----

. Create a Gitea custom resource:
+
[source,sh]
----
echo "apiVersion: gpte.opentlc.com/v1alpha1
kind: Gitea
metadata:
  name: repository
spec:
  giteaImageTag: 1.12.6
  postgresqlVolumeSize: 4Gi
  giteaVolumeSize: 4Gi
  giteaSsl: True" > $HOME/gitea-operator/config/samples/gitea-server.yaml
----

. Create the Custom Resource
+
[source,sh]
----
oc create -f $HOME/gitea-operator/config/samples/gitea-server.yaml -n gitea
----

. In the first window observe the operator code creating the application. You should see no errors.
+
Once the operator finishes the deploy it usually runs through the playbook one more time because the reconcile period will have already passed. Again you should see no errors.

. In the second window examine the Gitea custom resource:
+
[source,sh]
----
oc get gitea repository -o yaml -n gitea
----
+
.Sample Output
[source,texinfo]
----
[...]
spec:
  giteaImageTag: 1.12.6
  giteaSsl: true
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
status:
  conditions:
  - ansibleResult:
      changed: 0
      completion: 2020-11-17T20:19:00.686392
      failures: 0
      ok: 7
      skipped: 0
    lastTransitionTime: "2020-11-17T20:16:44Z"
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
----
+
You should see that the `ansibleResult` is successful.

. Delete the gitea repository again.
+
[source,sh]
----
oc delete gitea repository -n gitea
----

In the first window where the operator is running stop the operator by pressing `Ctrl-C`.

== Build the operator container image

Before you build the operator image you need to make a few adjustments to the project. When testing you ran the operator as a cluster admin. But when you run the opeator as a pod it uses the `default` service account in the project that it gets installed to. Because the operator needs to create/update/manipulate a number of Kubernetes objects you need to adjust the cluster role that grants the correct permissions to the operator pod.

. Update the file config/rbac/role.yaml:

* At the bottom of the file (below the line `# +kubebuilder:scaffold:rules`) add two more *apiGroups* sections.
** Add a section with api group `""`,  resources: `serviceaccounts`, `persistentvolumeclaims`, `configmaps` and `services` and all the verbs.
** The operator also creates a route for the application. Add a new section with api group `route.openshift.io`, resource `routes` and all the verbs.
+
The final file should look like this:
+
[source,sh]
----
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for gpte.opentlc.com/v1alpha1, Kind: Gitea
  ##
  - apiGroups:
      - gpte.opentlc.com
    resources:
      - giteas
      - giteas/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
# +kubebuilder:scaffold:rules
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - persistentvolumeclaims
      - configmaps
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
----

. By default the operator gets installed in project `gitea-operator-system`. 
+
Should you want to change the name of the project change the property `namespace` in the file `config/default/kustomization.yaml`. In this file you can also enable Prometheus monitoring for your operator.

. Make sure you are logged into Quay (use `docker login` instead of `podman login` on macOS).
+
[source,sh]
----
export QUAY_ID=<your quay id>
podman login -u ${QUAY_ID} quay.io
----
+
.Sample Output
[source,texinfo]
----
Password:
Login Succeeded!
----

. To build on Linux with `podman` instead of `docker` make sure that docker is symlink to podman:
+
[source,sh]
----
sudo ln -s $(which podman) /usr/bin/docker
----

. Build the operator container image
+
[source,sh]
----
make docker-build IMG=quay.io/$QUAY_ID/gitea-operator:v0.1.0
----
+
.Sample Output
[source,texinfo]
----
STEP 1: FROM quay.io/operator-framework/ansible-operator:v1.2.0
Getting image source signatures
Copying blob 1b8dabac56ed done
Copying blob 6500ac87b29f done
Copying blob 1ad976f609da done
Copying blob 35cdff969dbb done
Copying blob 7b50a21ef6e8 done
Copying blob 5c6ceb1ab474 done
Copying blob 87bde904b055 done
Copying config 43d6b2eb8d done
Writing manifest to image destination
Storing signatures
STEP 2: COPY requirements.yml ${HOME}/requirements.yml
2e1ad05f22d68707451d4abeccbdcbd9e773a143cfbff925fefce1e03acfbd07
STEP 3: RUN ansible-galaxy collection install -r ${HOME}/requirements.yml  && chmod -R ug+rwx ${HOME}/.ansible
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'community.kubernetes:0.11.1' to '/opt/ansible/.ansible/collections/ansible_collections/community/kubernetes'
Downloading https://galaxy.ansible.com/download/community-kubernetes-0.11.1.tar.gz to /opt/ansible/.ansible/tmp/ansible-local-633glr5il/tmpd8zyue_p
community.kubernetes (0.11.1) was installed successfully
Installing 'operator_sdk.util:0.1.0' to '/opt/ansible/.ansible/collections/ansible_collections/operator_sdk/util'
Downloading https://galaxy.ansible.com/download/operator_sdk-util-0.1.0.tar.gz to /opt/ansible/.ansible/tmp/ansible-local-633glr5il/tmpd8zyue_p
operator_sdk.util (0.1.0) was installed successfully
8b81a42578cb23f318543f57c6cf69d1382ad3a2da4a7d2d6a3a4e6a81033f41
STEP 4: COPY watches.yaml ${HOME}/watches.yaml
a7e8d43d462a8e3614518ae5c66d9db4311bf08dc00f4f22048f4ce96258bbc6
STEP 5: COPY roles/ ${HOME}/roles/
ba81b3451274988be1520c3f287b23f8cb6ecfb1c038999ef7c5f49f4e0805d4
STEP 6: COPY playbooks/ ${HOME}/playbooks/
STEP 7: COMMIT quay.io/wkulhanek/gitea-operator:v0.1.0
f23feacf02228814407c2345dcce4aec8490712e698425d73790d2e764ff46bf
----

. Push the image to the registry:
+
[source,sh]
----
make docker-push IMG=quay.io/$QUAY_ID/gitea-operator:v0.1.0
----

. Make sure the repository `$QUAY_ID/gitea-operator` in Quay is public.

== Deploy the Operator to your cluster

You can use the Operator SDK to deploy the operator to your cluster.

. Again make sure that you are logged in as a user with `cluster-admin` privileges.
. Deploy the operator to your cluster.
+
[source,sh]
----
make deploy IMG=quay.io/$QUAY_ID/gitea-operator:v0.1.0
----
+
.Sample Output
[source,sh]
----
cd config/manager && /home/cloud-user/gitea-operator/bin/kustomize edit set image controller=quay.io/wkulhanek/gitea-operator:v0.1.0
/home/cloud-user/gitea-operator/bin/kustomize build config/default | kubectl apply -f -
namespace/gitea-operator-system created
customresourcedefinition.apiextensions.k8s.io/giteas.gpte.opentlc.com unchanged
role.rbac.authorization.k8s.io/gitea-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/gitea-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/gitea-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/gitea-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/gitea-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/gitea-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/gitea-operator-proxy-rolebinding created
service/gitea-operator-controller-manager-metrics-service created
deployment.apps/gitea-operator-controller-manager created
----

. Find the operator pod:
+
[source,sh]
----
oc get pod -n gitea-operator-system
----
+
.Sample Output
[source,texinfo]
----
NAME                                                 READY   STATUS    RESTARTS   AGE
gitea-operator-controller-manager-65497c4564-z6x4m   2/2     Running   0          67s
----

. Tail the logs of the `manager` container in your operator pod:
+
[source,sh]
----
oc logs -f gitea-operator-controller-manager-65497c4564-z6x4m -c manager -n gitea-operator-system 
----

. In a second window re-create your gitea custom resource `repository`.
+
[source,sh]
----
oc create -f $HOME/gitea-operator/config/samples/gitea-server.yaml -n gitea
----

. Observe the logs from the operator. Once again there should be no errors.
+
Should you get permission errors make sure you double check the `role.yaml`.
+
[TIP]
====
If you need to make adjustments to the role you can just redeploy the operator after you made your changes:

[source,sh]
----
make deploy IMG=quay.io/$QUAY_ID/gitea-operator:v0.1.0
----
====

. Your operator is now running on the cluster and managing Giteas for the whole cluster.
+
Clean up the Gitea repository and operator before proceeding to the next section:
+
[source,sh]
----
oc delete -f $HOME/gitea-operator/config/samples/gitea-server.yaml -n gitea
oc delete project gitea
make undeploy IMG=quay.io/$QUAY_ID/gitea-operator:v0.1.0
----

== Operator Lifecycle manager

In this section you create the artifacts necessary to surface your operator in the OperatorHub on your cluster. This allows cluster administrators to install the operator into your cluster using the Operator Lifecycle Manager.

. Make sure you're logged into the cluster as a cluster-admin.
. Create the operator bundle. The bundle contains a number of YAML manifests that describe your operator.
+
[source,sh]
----
cd $HOME/gitea-operator
make bundle VERSION=0.1.0 IMG=quay.io/$QUAY_ID/gitea-operator:v0.1.0
----
+
.Sample Output
[source,texinfo]
----
operator-sdk generate kustomize manifests -q

Display name for the operator (required):
> Gitea Operator

Description for the operator (required):
> Gitea Operator - provided by Red Hat GPTE

Provider's name for the operator (required):
> Red Hat GPTE

Any relevant URL for the provider name (optional):
> www.redhat.com/partners

Comma-separated list of keywords for your operator (required):
> gitea,repository

Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
> Wolfgang Kulhanek:wkulhane@redhat.com

/home/wkulhane-redhat.com/gitea-operator/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.1.0
INFO[0000] Building annotations.yaml
INFO[0000] Writing annotations.yaml in /home/wkulhane-redhat.com/gitea-operator/bundle/metadata
INFO[0000] Building Dockerfile
INFO[0000] Writing bundle.Dockerfile in /home/wkulhane-redhat.com/gitea-operator
operator-sdk bundle validate ./bundle
INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
INFO[0000] All validation tests have completed successfully
----

. Build the bundle container image. This wraps all the generated YAML manifests into an OCI compliant container image. This container image is much easier to maintain than a bunch of YAML files (on macOS use `docker` instead of `podman`).
+
[source,sh]
----
podman build -f bundle.Dockerfile -t quay.io/$QUAY_ID/gitea-operator-bundle:v0.1.0 .
----

. Push the bundle image to the Quay registry and then validate that it looks correct (on macOS use `docker` instead of `podman`).
+
[source,sh]
----
podman push quay.io/$QUAY_ID/gitea-operator-bundle:v0.1.0
operator-sdk bundle validate quay.io/$QUAY_ID/gitea-operator-bundle:v0.1.0 -b podman 
----

. The next step is to create a catalog index image. There is a dedicated tool that helps with adding bundle images into an index image.
+
Download and install the `opm` tool:
+
.Linux (simple approach)
[source,sh]
----
export OPM_RELEASE=v1.15.1

curl -L https://github.com/operator-framework/operator-registry/releases/download/${OPM_RELEASE}/linux-amd64-opm -o ./opm

chmod +x ./opm
sudo chown root:root ./opm
sudo mv opm /usr/local/bin/opm
----
+
.macOS
[source,sh]
----
export OPM_RELEASE=v1.15.1

curl -L https://github.com/operator-framework/operator-registry/releases/download/$OPM_RELEASE/darwin-amd64-opm -o ./opm

chmod +x ./opm
mv opm ~/bin/opm
----
+
[NOTE]
====
On Linux the preferred way is to extract the `opm` tool from the officially built image for the version of your OpenShift cluster.

Create a file `auth.json` with your pull secret for the Red Hat registries. You can get that secret at https://try.openshift.com. Extract the opm tool from the most recent OpenShift operator registry image:

[source,sh]
----
REG_CREDS=./auth.json
oc image extract registry.redhat.io/openshift4/ose-operator-registry:v4.6 -a ${REG_CREDS} --path /usr/bin/opm:. --confirm
chmod +x ./opm
sudo chown root:root ./opm
sudo mv ./opm /usr/local/bin/opm
----
====

. Set your Quay ID and make sure you are still logged into Quay (on macOS use `docker` instead of `podman`):
+
[source,sh]
----
export QUAY_ID=<your quay id>
podman login -u $QUAY_ID quay.io
----

. Create the index image - this image contains just the bundle image for the gitea operator:
+
[NOTE]
On macOS you need to add the parameter `--build-tool docker` because `podman` does not exist for on macOS.
+
[source,sh]
----
opm index add \
    --bundles quay.io/$QUAY_ID/gitea-operator-bundle:v0.1.0 \
    --tag quay.io/$QUAY_ID/gitea-catalog:v0.1.0
----
+
.Sample Output
[source,texinfo]
----
INFO[0000] building the index                            bundles="[quay.io/wkulhanek/gitea-operator-bundle:v0.1.0]"
INFO[0000] resolved name: quay.io/wkulhanek/gitea-operator-bundle:v0.1.0
INFO[0000] fetched                                       digest="sha256:e162412eb27fc6ee5f3652fb34257665c4edaca4996b46bdae652d6548390c18"
INFO[0000] fetched                                       digest="sha256:a5eee87167b31eeae1a871816c0508bb62993b9cc7efc8a6103b5c4978961ef2"
INFO[0000] fetched                                       digest="sha256:904ad00eac728e50cb536beed56a0aba8f95fedb63f5acc8b2313306b347c597"
INFO[0000] fetched                                       digest="sha256:7507a2219790f2a1d9db6ab80a12ca382aea9c6bdc189b6dbba60713bc607ba2"
INFO[0000] fetched                                       digest="sha256:0d2abad01ace379dec43a23b0957c5c2ef3136c3dc3a724012e6e4bdbb996f29"
INFO[0000] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:904ad00eac728e50cb536beed56a0aba8f95fedb63f5acc8b2313306b347c597 2354 [] map[] <nil>}
INFO[0000] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:0d2abad01ace379dec43a23b0957c5c2ef3136c3dc3a724012e6e4bdbb996f29 368 [] map[] <nil>}
INFO[0000] unpacking layer: {application/vnd.docker.image.rootfs.diff.tar.gzip sha256:a5eee87167b31eeae1a871816c0508bb62993b9cc7efc8a6103b5c4978961ef2 449 [] map[] <nil>}
INFO[0000] Could not find optional dependencies file     dir=bundle_tmp225640724 file=bundle_tmp225640724/metadata load=annotations
INFO[0000] found csv, loading bundle                     dir=bundle_tmp225640724 file=bundle_tmp225640724/manifests load=bundle
INFO[0000] loading bundle file                           dir=bundle_tmp225640724/manifests file=gitea-operator-controller-manager-metrics-service_v1_service.yaml load=bundle
INFO[0000] loading bundle file                           dir=bundle_tmp225640724/manifests file=gitea-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml load=bundle
INFO[0000] loading bundle file                           dir=bundle_tmp225640724/manifests file=gitea-operator.clusterserviceversion.yaml load=bundle
INFO[0000] loading bundle file                           dir=bundle_tmp225640724/manifests file=gpte.opentlc.com_giteas.yaml load=bundle
INFO[0000] Generating dockerfile                         bundles="[quay.io/wkulhanek/gitea-operator-bundle:v0.1.0]"
INFO[0000] writing dockerfile: index.Dockerfile125385234  bundles="[quay.io/wkulhanek/gitea-operator-bundle:v0.1.0]"
INFO[0000] running podman build                          bundles="[quay.io/wkulhanek/gitea-operator-bundle:v0.1.0]"
INFO[0000] [podman build --format docker -f index.Dockerfile125385234 -t quay.io/wkulhanek/gitea-catalog:v0.1.0 .]  bundles="[quay.io/wkulhanek/gitea-operator-bundle:v0.1.0]"
(ansible-operator) [cloud-user@bastion gitea-operator]$
----

. Push the catalog image to the Quay repository (on macOS use `docker` instead of `podman`):
+
[source,sh]
----
podman push quay.io/$QUAY_ID/gitea-catalog:v0.1.0
----

. Make sure that the repos `gitea-catalog`, `gitea-operator-bundle` and `gitea-operator` in your Quay account are public.

. In order to use the catalog image from your OpenShift cluster you need to create a catalog source that points to your index image. `openshift-marketplace` is a good project to collect your catalog sources.
+
[source,sh]
----
echo "apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-gpte
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/$QUAY_ID/gitea-catalog:v0.1.0
  displayName: Red Hat GPTE" > $HOME/gitea-operator/catalog_source.yaml
----

. Create the Catalog Source in the cluster
+
[source,sh]
----
oc create -f $HOME/gitea-operator/catalog_source.yaml
----

. Log into the OpenShift Web Console, create a new project, navigate to the Operator Hub and you should see the new "Provider Type" and the Gitea Operator in the list of operators.

. You can now deploy the operator from the Operator Hub.


== TBD:

* CRD enhancements for oc explain
* Add icon and better description to Operator in Operator Hub
* Add example CR to the Operator Description

////
+
[source,sh]
----
wget https://github.com/go-gitea/gitea/raw/master/assets/logo.svg
----

Convert from svg to png and base64 encode
+
[source,sh]
----
pip3 install cairosvg
cairosvg -H 300 -W 300 -f png -o gitea.png logo.svg
base64 gitea.png > gitea-base64.png
----

Main kustomization file: gitea-operator/config/defaults/kustomization.yaml

CRD: $HOME/gitea-operator/config/crd/bases/gpte.opentlc.com_giteas.yaml
Kustomzation: $HOME/gitea-operator/config/crd/kustomization.yaml

Manifests:
Kustomization: $HOME/gitea-operator/config/manifests/kustomization.yaml
CSV: $HOME/gitea-operator/config/manifests/bases/gitea-operator.clusterserviceversion.yaml



=== Works
Update the Sample to be displayed when creating a Gitea from OLM:

[source,sh]
----
echo "apiVersion: gpte.opentlc.com/v1alpha1
kind: Gitea
metadata:
  name: repository
spec:
  postgresqlVolumeSize: 4Gi
  giteaVolumeSize: 4Gi
  giteaSsl: True" > $HOME/gitea-operator/config/samples/gpte_v1alpha1_gitea.yaml
----
Update bundle with `make bundle`
////
