== Installing Service Mesh Lab

.Goals

* Set up the Service Mesh *Technology Preview* 12 on your cluster (this renders your cluster *unsupported*!)
* Explore Service Mesh capabilities using the Bookinfo example.

[[labexercises]]
:numbered:

== Set up Service Mesh on your Cluster

[NOTE]
The installation instructions can be found at https://docs.openshift.com/container-platform/4.1/service_mesh/service_mesh_install/installing-ossm.html

Follow the instructions to deploy the Service Mesh into your cluster. The following are the steps necessary to get Service Mesh running.

. Install the Jaeger Operator
+
[source,sh]
----
oc new-project observability # create the project for the jaeger operator
oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/crds/jaegertracing_v1_jaeger_crd.yaml
oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/service_account.yaml
oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/role.yaml
oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/role_binding.yaml
oc create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/v1.13.1/deploy/operator.yaml
----

. Check that the Jaeger operator is running
+
[source,sh]
----
oc get pod -n observability
----
+
.Sample Output
[source,texinfo]
----
NAME                               READY   STATUS    RESTARTS   AGE
jaeger-operator-57d9d8774b-jsrtt   1/1     Running   0          36s
----

. Verify the Operator launched successfully.
+
[source,sh]
----
oc logs -n observability $(oc -n observability get pods -l name=jaeger-operator --output=jsonpath={.items..metadata.name})
----
+
.Sample Output
[source,texinfo]
----
time="2019-08-15T04:43:53Z" level=info msg=Versions arch=amd64 jaeger-operator=1.13.1 operator-sdk=v0.8.1 os=linux version=go1.12.5
time="2019-08-15T04:43:53Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-08-15T04:43:53Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=true
----

. Install the Kiali Operator. This command doesn't actually install Kiali. That is handled by the Red Hat OpenShift Service Mesh Operator.
+
[source,sh]
----
bash <(curl -L https://git.io/getLatestKialiOperator) --operator-image-version v1.0.0 --operator-watch-namespace '**' --accessible-namespaces '**' --operator-install-kiali false
----

. Create two projects for the Service Mesh Operator
+
[source,sh]
----
oc new-project istio-operator
oc new-project istio-system
----

. Install the Red Hat OpenShift Service Mesh Operator
+
[source,sh]
----
oc apply -n istio-operator -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.12/deploy/servicemesh-operator.yaml
----

. Check that the Service Mesh operator is running
+
[source,sh]
----
oc get pod -n istio-operator
----
+
.Sample Output
[source,texinfo]
----
NAME                              READY   STATUS    RESTARTS   AGE
istio-operator-7d77fcd9cc-qn84t   1/1     Running   0          48s
----

. Verify the Operator launched successfully.
+
[source,sh]
----
oc logs -n istio-operator $(oc -n istio-operator get pods -l name=istio-operator --output=jsonpath={.items..metadata.name})
----
+
.Sample Output
[source,texinfo]
----
{"level":"info","ts":1565844491.6164489,"logger":"cmd","caller":"manager/main.go:36","msg":"Go Version: go1.12.6"}
{"level":"info","ts":1565844491.6164849,"logger":"cmd","caller":"manager/main.go:37","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1565844491.6164901,"logger":"cmd","caller":"manager/main.go:38","msg":"operator-sdk Version: v0.2.1"}
{"level":"info","ts":1565844491.6167908,"logger":"leader","caller":"leader/leader.go:55","msg":"Trying to become the leader."}
{"level":"info","ts":1565844491.706609,"logger":"leader","caller":"leader/leader.go:103","msg":"No pre-existing lock was found."}
{"level":"info","ts":1565844491.71475,"logger":"leader","caller":"leader/leader.go:127","msg":"Became the leader."}
{"level":"info","ts":1565844491.7164183,"logger":"cmd","caller":"manager/main.go:90","msg":"Registering Components."}

[...]

{"level":"info","ts":1565844492.0125067,"logger":"kubebuilder.controller","caller":"controller/controller.go:153","msg":"Starting workers","Controller":"controlplane-controller","WorkerCount":1}
{"level":"info","ts":1565844492.5899532,"logger":"kubebuilder.admission.cert.writer","caller":"writer/fs.go:117","msg":"cert directory /tmp/cert doesn't exist, creating"}
----

. Deploy the Control Plane by creating a Custom Resource file.
+
[TIP]
Full documentation for the Custom Resource is available at https://docs.openshift.com/container-platform/4.1/service_mesh/service_mesh_install/installing-ossm.html#ossm-cr-example_installing-ossm
+
. Create the custom resource file `$HOME/service-mesh.yaml` to create the Service Mesh.
+
Note the following:
* You are configuring a cluster-wide service mesh (multitenant: false)
* 3Scale is enabled
* You are configuring a user `admin` with password `r3dh4t1!` for *Kiali*:
* You are specifying a specific tag for the Jaeger pods (0.13.1). This is because otherwise the pods would be configured for 0.12 - and those tags don't exist in the Red Hat registry resulting in failed pods.
+
[source,texinfo]
----
cat << EOF >$HOME/service-mesh.yaml
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: global-mesh
spec:
  threeScale:
    enabled: true

  istio:
    global:
      multitenant: false
      disablePolicyChecks: false
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      dashboard:
        user: admin
        passphrase: r3dh4t1!
    tracing:
      enabled: true
      jaeger:
        tag: 1.13.1
EOF
----

. Now create the Service Mesh installation.
+
[source,sh]
----
oc create -f $HOME/service-mesh.yaml -n istio-system
----

. Watch the progress of the deployment
+
[source,sh]
----
watch oc get pods -n istio-system
----
+
It will take a minute or two before pods start appearing and you may see some pods temporarily in `Error` and `CrashLoopBackoff` states - which should resolve itselve within a few seconds. The whole installation process can take more than 5 minutes.

. Once you see the following pods all running successfully, the service mesh has been installed successfully.
+
[source,texinfo,nowrap=true]
----
NAME                                      READY   STATUS    RESTARTS   AGE
elasticsearch-0                           1/1     Running   0          7m34s
grafana-694d54c786-5dgmm                  2/2     Running   0          4m44s
istio-citadel-7658c96954-ml58z            1/1     Running   0          8m12s
istio-egressgateway-d759556b8-6pdmf       1/1     Running   0          5m54s
istio-galley-7cf565999f-zjgx5             1/1     Running   0          7m2s
istio-ingressgateway-bc97545d5-jx8ng      1/1     Running   0          5m53s
istio-pilot-756c96bbfc-j8gft              2/2     Running   0          6m27s
istio-policy-f78b45cb5-h6rkk              2/2     Running   0          6m39s
istio-sidecar-injector-5bccb75987-qbgp8   1/1     Running   0          5m1s
istio-telemetry-f4c6f99d6-vl2q2           2/2     Running   0          6m39s
jaeger-collector-7f4fcf6c95-9nkd7         1/1     Running   2          7m34s
jaeger-query-847887c557-g2r5h             3/3     Running   2          7m34s
kiali-54ff784b57-dc7nc                    1/1     Running   0          4m5s
prometheus-7b89468cf6-6jvzx               2/2     Running   0          7m56s
----

. Examine the created routes in the `istio-system` project
+
[source,sh]
----
oc get routes -n istio-system
----
+
.Sample Output
[source,texinfo,nowrap=true]
----
NAME                   HOST/PORT                                                                   PATH   SERVICES               PORT    TERMINATION   WILDCARD
grafana                grafana-istio-system.apps.cluster-1d1a.sandbox21.opentlc.com                       grafana                <all>   reencrypt     None
istio-ingressgateway   istio-ingressgateway-istio-system.apps.cluster-1d1a.sandbox21.opentlc.com          istio-ingressgateway   80                    None
jaeger                 jaeger-istio-system.apps.cluster-1d1a.sandbox21.opentlc.com                        jaeger-query           <all>   reencrypt     None
kiali                  kiali-istio-system.apps.cluster-1d1a.sandbox21.opentlc.com                         kiali                  <all>   reencrypt     None
prometheus             prometheus-istio-system.apps.cluster-1d1a.sandbox21.opentlc.com                    prometheus             <all>   reencrypt     None
tracing                tracing-istio-system.apps.cluster-1d1a.sandbox21.opentlc.com                       tracing                <all>   edge          None
----

. You will see routes for *Grafana*, *Prometheus* and *Kiali* amongst others.

. Open the *Kiali* Interface in a web browser using the kiali route (making sure to use `https`). Use 'admin' as the user id and 'r3dh4t1!' as the password to log in.

== Bookinfo Tutorial

Now that the service mesh is successfully deployed on your cluster you can follow the *Bookinfo* tutorial to explore the various capabilities that Istio offers.

You can find the tutorial at https://docs.openshift.com/container-platform/4.1/service_mesh/service_mesh_install/ossm-example-bookinfo.html.